M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon 06 Jul 2026 01:27:41 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-06T13:27:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.0945Y-2.126
X4.0945Y-5.748
X7.7165Y-2.126
X7.7165Y-5.748
M30
